### ISSUE TITLE
Is the demo functional?

### ISSUE THREAD

**Issue by flooie** [chamkank/flask-chatterbot#1]
Is the demo functional?

**Comment by chamkank** [comment]
Yep! It hasn't been trained beyond the corpus so the answers you are seeing are from multiple people using the demo with different inputs.

**Comment by flooie** [comment]
- so when I tried to run it - I never saw an input field... is that because this is just the backend?

**Comment by chamkank** [comment]
If you're running it locally, you can pass input using the url.

Ex: [http://localhost:5000/get/how%20are%20you?](http://localhost:5000/get/how%20are%20you?)

**Comment by naivefun** [comment]
I'm getting strange answers like:
Q: how are you?
A: Who? Who is but a form following the function of what

Q: what day is today?
A: Artificial Intelligence is the branch of engineering and science devoted to constructing machines that think.

**Comment by chamkank** [comment]
Those are the responses selected by the [logic adapters](http://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#module-chatterbot.response_selection) when that bot doesn't have a lead. For more info check out [this response](https://github.com/gunthercox/ChatterBot/issues/832#issuecomment-314052937) on how the bot works. 

For example, you can train the bot to answer "How are you?" like this:
`chatbot.train([
    "How are you?",
    "I am good",
])
`

**Comment by naivefun** [comment]
I see. But I did call `train` with English corpus and English.Greetings corpus which is built-in right?

**Comment by chamkank** [comment]
Yeah, for the English corpus you can find all of the queries and their responses [here](https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data/english). Try any of the exact queries in any of the files there and you'll see their responses.

**Comment by naivefun** [comment]
IC. I tried 'how are you?' not 'how are you doing?'. I'm surprised this doesn't match in best matches adapter.

**Comment by chamkank** [comment]
That' s because "how are you?" is closer to "who are you?" than it is to "how are you doing?". The response to "Who are you?" is what results in "Who? Who is but a form following the function of what" (see (conversations.yml)[https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/conversations.yml]).
