### ISSUE TITLE
deploying with python anywhere

### ISSUE THREAD

**Issue by priyanka22kar** [chamkank/flask-chatterbot#10]
@chamkank when I try to execute app.py with python anywhere I get the below error

dbapi_connection.execute('PRAGMA journal_mode=WAL')
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot change into wal mode from within a transaction (Background on this error at: ht
tp://sqlalche.me/e/e3q8)

**Comment by gunthercox** [comment]
Hi @priyanka22kar, this might be an issue with the ChatterBot library itself https://github.com/gunthercox/ChatterBot/issues/1162

I'll be working on releasing an update to fix this soon.

**Comment by priyanka22kar** [comment]
@gunthercox  thankyou for your reply
