### ISSUE TITLE
Chatterbot Can't speak Chinese ???

### ISSUE THREAD

**Issue by qiankun30** [chamkank/flask-chatterbot#19]
Chatterbot Can't speak Chinese ???

**Comment by edwardinubuntu** [comment]
The Chatterbot is a training bot, you have to design questions and answers. Check out more at here: https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data/chinese

**Comment by qiankun30** [comment]
好的。谢谢！
