### ISSUE TITLE
If I upgrade the modules to the latest version it shows various errors

### ISSUE THREAD

**Issue by anilneeluri** [chamkank/flask-chatterbot#5]
How can it be solved if I upgrade it to the latest version

**Comment by gunthercox** [comment]
@anilneeluri You should include a copy of the errors you are getting so that we can help you.

**Comment by anilneeluri** [comment]
Firstly I did not find a way to use the storage adapters in the Chatbot of that version of the chatterbot(0.3.6). How can it be done?(if the storage adapters are present in that version)

**Comment by edwardinubuntu** [comment]
Chatterbot has latest version 0.7.5, you can use pip3 to install.

$pip3 show chatterbot
Name: ChatterBot
Version: 0.7.5
Summary: 
Home-page: None
Author: None
Author-email: None
License: None
Location: /usr/local/lib/python3.6/site-packages
Requires: nltk, python-twitter, jsondatabase, pymongo, sqlalchemy, python-dateutil, chatterbot-corpus

If you use storage adapters like mongo db, needed to setup reference parameter for it while building chatbot.

```
mongodb_name = os.environ.get('MONGODB_NAME')
mongodb_uri = os.environ.get('MONGODB_URI')
my_bot = ChatBot("my_bot",
                     storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
                     logic_adapters=[
                         {
                             'import_path': "chatterbot.logic.BestMatch"
                         }
                     ],
                     database=mongodb_name,
                     database_uri=mongodb_uri
                     )
```

You may find those keyword in self.kwargs.get
https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/storage/mongodb.py

**Comment by anilneeluri** [comment]
Traceback (most recent call last):
  File "C:/Users/Colorssoftware/PycharmProjects/chatbot(2.7)/flask_chatbot.py", line 3, in <module>
    app = create_app(debug=True)
  File "C:\Users\Colorssoftware\PycharmProjects\chatbot(2.7)\app\__init__.py", line 13, in create_app
    from .machine_learning import machine_learning as machine_learning_blueprint
  File "C:\Users\Colorssoftware\PycharmProjects\chatbot(2.7)\app\machine_learning\__init__.py", line 5, in <module>
    from app.machine_learning import events, routes
  File "C:\Users\Colorssoftware\PycharmProjects\chatbot(2.7)\app\machine_learning\events.py", line 8, in <module>
    database = 'english-database')
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 43, in __init__
    self.add_adapter(storage_adapter, **kwargs)
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 62, in add_adapter
    NewAdapter = import_module(adapter)
  File "C:\Python27\lib\site-packages\chatterbot\utils\module_loading.py", line 12, in import_module
    module = importlib.import_module(module_path)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named storage****


This is what I'm getting as a error when I use this project with the latest chatterbot module and use a storage adapter

**Comment by gunthercox** [comment]
@anilneeluri What command did you use to do the upgrade?

**Comment by anilneeluri** [comment]
I used "pip install chatterbot  --upgrade" as I installed the older version 0.3.6 for the sake of this project

**Comment by gunthercox** [comment]
Try the following. Let me know if you get any errors in your terminal when running them.

```
 pip uninstall chatterbot
 pip install chatterbot --no-cache-dir
```

**Comment by anilneeluri** [comment]
pardon. I did it by using pycharm interpreter. If I use the above command it upgrades the related modules with it. So had to do it using Pycharm interpreter.

**Comment by gunthercox** [comment]
Are you also running your code in Pycharm? I'm fairly certain that Pycharm also installs Python 3.

I'd recommend making sure that your python interpreter is set to the correct version of Python in pycharm. https://www.jetbrains.com/help/pycharm/2017.1/configuring-python-interpreter-for-a-project.html

One reason that you may be seeing this issue because the old version of ChatterBot is installed for Python 3 but the code is being executed in Python 2.7

***

This is a difficult error to debug, but it might help to try running these commands without Pycharm so that you can be sure of the Python environment.

**Comment by anilneeluri** [comment]
I have run the code using python2.7 itself in the pycharm . We can specify the python version that is to be used for that particular project. My only question is that, can we use Mongodb storage adapter for this?

**Comment by anilneeluri** [comment]
It works. Thanks.
