### ISSUE TITLE
How can I make it run in web browser of another system

### ISSUE THREAD

**Issue by priyanka22kar** [chamkank/flask-chatterbot#9]
I am new to chatterbot with flask
and running flask applications
I executed the app.py on my system , it works fine 
the app is running on a given URL
but I want to make it execute on other systems web browser too 
How can I do it?
Please help 
Thank you
@chamkank

**Comment by chamkank** [comment]
Hey there,

You'll have to host the app on a web server if you want other computers to be able to see it. There are a couple of options for this - you can find them listed here: http://flask.pocoo.org/docs/0.12/deploying/#hosted-options

The quickest one would probably be [PythonAnywhere](https://www.pythonanywhere.com/), here's a guide for it: https://help.pythonanywhere.com/pages/Flask/

**Comment by priyanka22kar** [comment]
thank you so much for your reply 
I am trying it with pythonanywhere
@chamkank

**Comment by chamkank** [comment]
@priyanka22kar No problem, feel free to reopen this issue if you have any more questions
